### ISSUE TITLE
Some ideas for your zshrc

### ISSUE THREAD

**Issue by afh** [awwalker/dotfiles#14]
* Use `path` instead of `PATH`
```
path <S> <Z> (PATH <S>)
An array (colon-separated list) of directories to search for commands. When this parameter is set, each directory is scanned and all files found are put in a hash table.
```
see [zsh: Parameters Used by the Shell](url)
* set `alias vim=$EDITOR` in https://github.com/awwalker/dotfiles/blob/master/.zshrc#L36
* Use self deleting shell functions for nvm / node related commands
```
if [ -d "$NVM_DIR" ]; then
  function _njs() {
    local -r cmd=$1; [[ $# -gt 0 ]] && shift
    unfunction $cmd
    source "$NVM_DIR"/nvm.sh
    [[ -f "$PWD/.nvmrc" ]] && nvm use >/dev/null
    $cmd $*
  }
  function nvm() { _njs $0 $* }
  function npm() { _njs $0 $* }
  function npx() { _njs $0 $* }
  function node() { _njs $0 $* }
  function yarn() { _njs $0 $* }
fi
```
* Personally I prefer using `$()` over backticks for subshell invocations as the backticks are hard to spot and do not allow nested subshells see https://github.com/awwalker/dotfiles/blob/master/.zshrc#L105
* Surely you meant `bindkey -v` in https://github.com/awwalker/dotfiles/blob/master/.zshrc#L135 ;)

**Comment by awwalker** [comment]
- ah `path` instead of `PATH` looks cool
- d'oh of course `$EDITOR`
- oh I've never seen self deleting shell functions before I'll give those a try for sure. 
- `$()` is probably the safer way to go
- hahaha `bindkey -e` I think because I was used to being able to `ctrl-R`for reverse history look up in the shell. I think this comes from my first job ever being tutored by a pair of equally influential and devout emacs and vim users and just grabbing what bits and pieces I could from both

**Comment by afh** [comment]
Oh yes `CTRL-R` is a must-have using `bindkey '^R' history-incremental-search-backward` works well for me in combination with `bindkey -v`
